name: Build

on:
  push:
    branches:
      - "master"
    tags:
      - "!*" # not a tag push
  pull_request:
    branches:
      - "master"

jobs:
  run-tests:
    if: ${{ always() }}
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneLinux64
        scriptBackend:
          - Mono2x
          - IL2CPP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: UnitTestCli_${{ matrix.targetPlatform }}_${{ matrix.scriptBackend }}
          path: ./bin/UnitTest/${{ matrix.targetPlatform }}_${{ matrix.scriptBackend }}
      - run: 'ls -ld ./bin/UnitTest/${{ matrix.targetPlatform }}_${{ matrix.scriptBackend }}'
      - run: 'chmod +x ./bin/UnitTest/${{ matrix.targetPlatform }}_${{ matrix.scriptBackend }}/test'
      - name: Execute UnitTest (${{ matrix.targetPlatform }}, ${{ matrix.scriptBackend }})
        run: ./bin/UnitTest/${{ matrix.targetPlatform }}_${{ matrix.scriptBackend }}/test