name: Build

on:
  push:
    branches:
      - "master"
    tags:
      - "!*" # not a tag push
  pull_request:
    branches:
      - "master"

jobs:
  generate-environments:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/checkout@v2
      - run: node ./generate-environments.js
        with:
          working-directory: ./.github/workflows
      - name: Read environments.json
        id: environments
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.github/workflows/environments.json
      - id: set-matrix
        run: echo "::set-output name=matrix::${{ steps.environments.outputs.content }}"
  restore-sources:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v1
        name: Set up Docker Buildx
        id: buildx
        with:
          buildx-version: latest
          qemu-version: latest
      - uses: actions/checkout@v2
      - name: Generate foundation for tests
        run: docker buildx build --output . ./Dependencies
      - uses: actions/upload-artifact@v2
        with:
          name: restored-sources
          path: |
            ./
            !./.git/
          retention-days: 1
  build-unity:
    if: ${{ always() }}
    needs: [restore-sources, generate-environments]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack: ${{fromJSON(needs.generate-environments.outputs.matrix)}}
    name: build-unity-${{ matrix.targetPlatform }}-${{ matrix.scriptBackend }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: restored-sources
          path: .
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}-${{ matrix.scriptBackend }}
          restore-keys:
            Library-${{ matrix.targetPlatform }}-
            Library-
      # /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -executeMethod UnitTestBuilder.BuildUnitTest /headless /ScriptBackend Mono2x /BuildTarget StandaloneLinux64
      - name: Build UnitTest (${{ matrix.targetPlatform }}, ${{ matrix.scriptBackend }})
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{secrets.UNITY_LICENSE}}
        with:
          projectPath: ./
          unityVersion: 2021.2.0f1
          targetPlatform: ${{ matrix.targetPlatform }}
          buildMethod: UnitTestBuilder.BuildUnitTest
          customParameters: /headless /ScriptBackend ${{ matrix.scriptBackend }}
          versioning: None
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.buildArtifactName }}
          path: |
            ${{ matrix.buildArtifactPath }}
            !${{ matrix.buildArtifactPath }}/test_BackUpThisFolder_ButDontShipItWithYourGame
          retention-days: 1
  run-tests-linux:
    needs: [build-unity, generate-environments]
    strategy:
      fail-fast: false
      matrix:
        stack: ${{fromJSON(needs.generate-environments.outputs.matrix)}}
    if: ${{ matrix.runTests }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ matrix.buildArtifactPath }}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.buildArtifactName }}
          path: ${{ matrix.buildArtifactPath }}
      - run: 'chmod +x ./test'
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Execute UnitTest (${{ matrix.targetPlatform }}, ${{ matrix.scriptBackend }})
        if: ${{ matrix.os != 'macos-latest' }}
        run: ./test
      - name: Execute UnitTest (${{ matrix.targetPlatform }}, ${{ matrix.scriptBackend }})
        if: ${{ matrix.os == 'macos-latest' }}
        run: open -a ./test.app