name: Publish

on:
  workflow_dispatch: {}

jobs:
  split-upm:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v2
      - name: split upm branch
        run: |
          git subtree split -P "$PKG_ROOT" -b upm
          git push -fu origin upm
        env:
          PKG_ROOT: Assets/Src/Scripts
