name: Unity-Build

on:
  push:
    branches:
      - "master"
    tags:
      - "!*" # not a tag push
  pull_request:
    branches:
      - "master"

jobs:
  build-unity:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: docker/setup-buildx-action@v1
        name: Set up Docker Buildx
        id: buildx
        with:
          buildx-version: latest
          qemu-version: latest
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate foundation for tests
        run: docker buildx build --output . ./Dependencies
      - uses: actions/upload-artifact@v2
        with:
          name: restored-sources
          path: |
            ./
            !./.git/