name: Unity-Build

on:
  push:
    branches:
      - "master"
    tags:
      - "!*" # not a tag push
  pull_request:
    branches:
      - "master"

jobs:
  build-unity:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: docker/setup-buildx-action@v1
        name: Set up Docker Buildx
        id: buildx
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - uses: actions/checkout@v2
      - name: Generate foundation for tests
        run: docker buildx build --output . ./Dependencies
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-Linux64-Mono2x
      # Execute scripts: Linux64/Mono2x
      # /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -executeMethod UnitTestBuilder.BuildUnitTest /headless /ScriptBackend Mono2x /BuildTarget StandaloneLinux64
      - name: Build UnitTest(Linux64, mono)
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{secrets.UNITY_LICENSE}}
        with:
          projectPath: ./
          unityVersion: 2021.2.0f1
          targetPlatform: StandaloneLinux64
          buildMethod: UnitTestBuilder.BuildUnitTest
          customParameters: /headless /ScriptBackend Mono2x
          versioning: None
      - name: Execute UnitTest
        run: ./bin/UnitTest/StandaloneLinux64_Mono2x/test
