name: Unity-Build

on:
  workflow_run:
    workflows: ["Restore-Sources"]
    branches: [master]
    types:
      - completed

jobs:
  build-unity:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneLinux64
        scriptBackend:
          - Mono2x
          - IL2CPP
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: restored-sources
          path: .
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}-${{ matrix.scriptBackend }}
          restore-keys:
            Library-${{ matrix.targetPlatform }}-
            Library-
      # /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -executeMethod UnitTestBuilder.BuildUnitTest /headless /ScriptBackend Mono2x /BuildTarget StandaloneLinux64
      - name: Build UnitTest (${{ matrix.targetPlatform }}, ${{ matrix.scriptBackend }})
        uses: game-ci/unity-builder@v2.0-alpha-6
        env:
          UNITY_LICENSE: ${{secrets.UNITY_LICENSE}}
        with:
          projectPath: ./
          unityVersion: 2021.2.0f1
          targetPlatform: ${{ matrix.targetPlatform }}
          buildMethod: UnitTestBuilder.BuildUnitTest
          customParameters: /headless /ScriptBackend ${{ matrix.scriptBackend }}
          versioning: None
      - uses: actions/upload-artifact@v2
        with:
          name: UnitTestCli_${{ matrix.targetPlatform }}_${{ matrix.scriptBackend }}
          path: ./bin/UnitTest/${{ matrix.targetPlatform }}_${{ matrix.scriptBackend }}
