name: Unity-Test

on:
  workflow_run:
    workflows: ["Unity-Build"]
    branches: [master]
    types:
      - completed
on:
  workflow_dispatch: {}

jobs:
  build-unity:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneLinux64
        scriptBackend:
          - Mono2x
          - IL2CPP
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: UnitTestCli_${{ matrix.targetPlatform }}_${{ matrix.scriptBackend }}
          path: .
      - name: Execute UnitTest (${{ matrix.targetPlatform }}, ${{ matrix.scriptBackend }})
        run: ./test
